// SPC v1 and CKC v1 field sizes as per specification for parsing
const PS_V1_ASSET_ID_MIN_SZ = 2
const PS_V1_VERSION_SZ = 4
const PS_V1_RESERVED_SZ = 4
const PS_V1_SPC_DATA_LENGTH_SZ = 4
const PS_V1_CKC_DATA_LENGTH_SZ = 4
const PS_V1_PROTOCOL_VERSION_USED_SZ = 4
const PS_V1_TRANSACTION_ID_SZ = 8
const PS_V1_SKR1_INTEGRITY_SZ = 16
const PS_V1_CLI_REF_TIME_SZ = 16
const PS_V1_HASH_SZ = 20
const PS_V1_R2_SZ = 21
const PS_V1_R1_SZ = 44
const PS_V1_R1_PADDING_SZ = 64 - PS_V1_R1_SZ
const PS_V1_SKR1_SZ = 112
const PS_V1_WRAPPED_KEY_SZ = 128
const PS_V1_ASSET_ID_MAX_SZ = 200
const PS_V1_STREAMING_REQUIRED_SZ = 8

// TLLV (Tag-Length-Length-Value) Size
const PS_TLLV_TAG_SZ = 8
const PS_TLLV_TOTAL_LENGTH_SZ = 4
const PS_TLLV_VALUE_LENGTH_SZ = 4
const PS_TLLV_HEADER_SZ =
  PS_TLLV_TAG_SZ + PS_TLLV_TOTAL_LENGTH_SZ + PS_TLLV_VALUE_LENGTH_SZ

const PS_TLLV_DURATION_LEASE_SZ = 4
const PS_TLLV_DURATION_CK_SZ = 4
const PS_TLLV_DURATION_KEY_TYPE_SZ = 4
const PS_TLLV_DURATION_RESV_SZ = 4
const PS_TLLV_DURATION_VALUE_SZ =
  PS_TLLV_DURATION_LEASE_SZ +
  PS_TLLV_DURATION_CK_SZ +
  PS_TLLV_DURATION_KEY_TYPE_SZ +
  PS_TLLV_DURATION_RESV_SZ
const PS_TLLV_DURATION_PADDING_SZ = 16

// Offline Key TLLV
const PS_TLLV_OFFLINEKEY_VALUE_SZ = 32
const PS_TLLV_OFFLINEKEY_PADDING_SZ = 16
const PS_TLLV_OFFLINEKEY_TLLV_VERSION = 1
const PS_TLLV_OFFLINEKEY_CONTENTID_SZ = 16

// Standard sizes
const PS_AES128_KEY_SZ = 16
const PS_AES128_IV_SZ = 16

// Other defines
const PS_V1_VERSION = 1

// Internal TLLV presence flags for SPC parsing
const FLAG_TAG_SK_R1 = 0x00000001
const FLAG_TAG_AR = 0x00000002
const FLAG_TAG_R2 = 0x00000004
const FLAG_TAG_ASSET_ID = 0x00000008
const FLAG_TAG_TRANS_ID = 0x00000010
const FLAG_TAG_PROT_V_USED = 0x00000020
const FLAG_TAG_PROT_V_SUPPORTED = 0x00000040
const FLAG_TAG_RET_REQ = 0x00000100
const FLAG_TAG_SK_R1_INTEG = 0x00000200
const FLAG_TAG_CLIENT_REF_TIME = 0x00000400
const FLAG_TAG_STREAMINGREQUIRED = 0x00000800
const FLAG_TAG_SYNC_RENTAL = 0x00001000
const FLAG_SPC_REQUIRED_TAGS_V1 =
  FLAG_TAG_SK_R1 |
  FLAG_TAG_AR |
  FLAG_TAG_R2 |
  FLAG_TAG_ASSET_ID |
  FLAG_TAG_TRANS_ID |
  FLAG_TAG_PROT_V_USED |
  FLAG_TAG_PROT_V_SUPPORTED |
  FLAG_TAG_RET_REQ |
  FLAG_TAG_SK_R1_INTEG

module.exports = {
  PS_V1_ASSET_ID_MIN_SZ,
  PS_V1_VERSION_SZ,
  PS_V1_RESERVED_SZ,
  PS_V1_SPC_DATA_LENGTH_SZ,
  PS_V1_CKC_DATA_LENGTH_SZ,
  PS_V1_PROTOCOL_VERSION_USED_SZ,
  PS_V1_TRANSACTION_ID_SZ,
  PS_V1_SKR1_INTEGRITY_SZ,
  PS_V1_CLI_REF_TIME_SZ,
  PS_V1_HASH_SZ,
  PS_V1_R2_SZ,
  PS_V1_R1_SZ,
  PS_V1_R1_PADDING_SZ,
  PS_V1_SKR1_SZ,
  PS_V1_WRAPPED_KEY_SZ,
  PS_V1_ASSET_ID_MAX_SZ,
  PS_V1_STREAMING_REQUIRED_SZ,
  PS_TLLV_TAG_SZ,
  PS_TLLV_TOTAL_LENGTH_SZ,
  PS_TLLV_VALUE_LENGTH_SZ,
  PS_TLLV_HEADER_SZ,
  PS_TLLV_DURATION_LEASE_SZ,
  PS_TLLV_DURATION_CK_SZ,
  PS_TLLV_DURATION_KEY_TYPE_SZ,
  PS_TLLV_DURATION_RESV_SZ,
  PS_TLLV_DURATION_VALUE_SZ,
  PS_TLLV_DURATION_PADDING_SZ,
  PS_TLLV_OFFLINEKEY_VALUE_SZ,
  PS_TLLV_OFFLINEKEY_PADDING_SZ,
  PS_TLLV_OFFLINEKEY_TLLV_VERSION,
  PS_TLLV_OFFLINEKEY_CONTENTID_SZ,
  PS_AES128_KEY_SZ,
  PS_AES128_IV_SZ,
  PS_V1_VERSION,
  FLAG_TAG_SK_R1,
  FLAG_TAG_AR,
  FLAG_TAG_R2,
  FLAG_TAG_ASSET_ID,
  FLAG_TAG_TRANS_ID,
  FLAG_TAG_PROT_V_USED,
  FLAG_TAG_PROT_V_SUPPORTED,
  FLAG_TAG_RET_REQ,
  FLAG_TAG_SK_R1_INTEG,
  FLAG_TAG_CLIENT_REF_TIME,
  FLAG_TAG_STREAMINGREQUIRED,
  FLAG_TAG_SYNC_RENTAL,
  FLAG_SPC_REQUIRED_TAGS_V1
}